services:
  api01: &api
    image: gustmrg/rinha-backend-2025
    container_name: rinha_api01
    hostname: api01
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=rinha
      - DB_PASSWORD=rinha
      - DB_NAME=rinha
      - DB_MAX_POOL_SIZE=20     
      - DB_MIN_POOL_SIZE=5     
      - DB_CONNECTION_TIMEOUT=15 
      - DB_COMMAND_TIMEOUT=10    
      - DB_CONNECTION_IDLE_LIFETIME=300
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
    networks:
      - rinha-network
      - payment-processor
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: "80MB"

  api02:
    <<: *api
    container_name: rinha_api02
    hostname: api02

  db:
    image: postgres:17-alpine
    container_name: rinha_db
    hostname: db
    restart: always
    environment:
      - POSTGRES_PASSWORD=rinha
      - POSTGRES_USER=rinha
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: |
      postgres 
      -c max_connections=80           
      -c shared_buffers=24MB          
      -c effective_cache_size=80MB    
      -c work_mem=600kB               
      -c maintenance_work_mem=6MB     
      -c synchronous_commit=off
      -c max_wal_senders=0 
      -c wal_level=minimal
      -c checkpoint_completion_target=0.9
      -c wal_buffers=8MB              
      -c default_statistics_target=50 
      -c random_page_cost=1.1
      -c effective_io_concurrency=100 
      -c autovacuum=off           
      -c fsync=off                    
    networks:
      - rinha-network
      - payment-processor
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rinha -d rinha"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: "0.65"
          memory: "175MB"

  nginx:
    image: nginx:1.27.0-alpine
    container_name: rinha_nginx
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    networks:
      - rinha-network
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "15MB"

networks:
  payment-processor:
    external: true
  rinha-network:
    driver: bridge
