version: "3.9"

services:
  api01: &api
    image: gustmrg/rinha-backend-2025
    container_name: rinha_api01
    hostname: api01
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=rinha
      - DB_PASSWORD=rinha
      - DB_NAME=rinha
    networks:
      - rinha-network
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.40"
          memory: "85MB"

  api02:
    <<: *api
    container_name: rinha_api02
    hostname: api02

  db:
    image: postgres:17-alpine
    container_name: rinha_db
    hostname: db
    restart: always
    environment:
      - POSTGRES_PASSWORD=rinha
      - POSTGRES_USER=rinha
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    command: postgres -c max_connections=450 -c shared_buffers=32MB -c effective_cache_size=96MB -c work_mem=3MB -c maintenance_work_mem=12MB -c synchronous_commit=off -c fsync=off
    networks:
      - rinha-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rinha -d rinha"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "130MB"

  nginx:
    image: nginx:1.27.0-alpine
    container_name: rinha_nginx
    ports:
      - "9999:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    networks:
      - rinha-network
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "15MB"

networks:
  payment-processor:
    external: true
  rinha-network:
    driver: bridge
